service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: bblfsh-play2-production
    kubernetes.io/tls-acme: "true"
  hosts:
    - play.bblf.sh
  tls:
    - secretName: play-bblf-sh-tls
      hosts:
        - play.bblf.sh


affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                #This value depends of the HELM_RELEASE defined in .travis.yml should be ${HELM_RELEASE}-${CHART_NAME}
                - play-bblfsh-web
        topologyKey: kubernetes.io/hostname

replicaCount: 2

nodeSelector:
  cloud.google.com/gke-nodepool: default-pool

bblfshd-sidecar:
  metrics:
    enabled: true
  image:
    tag: v2.14.0-drivers
